# Generated by Django 2.2.4 on 2019-11-11 08:24

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='题目', max_length=50, null=True, verbose_name='题目')),
                ('content', ckeditor.fields.RichTextField(verbose_name='文章内容')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='喜欢数')),
                ('aritcle_brief', models.TextField(default='', max_length=500, verbose_name='文章概述')),
                ('article_front_image', models.ImageField(blank=True, null=True, upload_to='article/images/', verbose_name='封面图')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('author', models.CharField(default='', help_text='作者', max_length=20, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(default='', help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('name', models.ForeignKey(default='', help_text='文章名', on_delete=django.db.models.deletion.SET_DEFAULT, to='articles.Article', verbose_name='文章名')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '封面图',
                'verbose_name_plural': '封面图',
            },
        ),
        migrations.CreateModel(
            name='ArticleCatergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='articles.ArticleCatergory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleCatergory', verbose_name='文章类别'),
        ),
    ]
